### ISSUE TITLE
Jade

### ISSUE THREAD

**Issue by sathomps** [improving-minnesota/angular-timesheet#7]
I would like to remove Jade from the training class - makes it simpler and teams, once they are comfortable with developing Angular projects, can add it at a later date.

**Comment by brucecoddington** [comment]
This works, we need to: 
1. Compile the index.jade before the class and have it in the templates directory for demoing. Since we're not showing the development environments until the very last day, we can also keep it out of the 'watch' task.  
2. Serve the index.html instead of jade so that students can actually make changes and see the results.

**Comment by brucecoddington** [comment]
done
